import type { Metadata } from "next";
import "./globals.css";
import { YekanBakh } from "@/utils/fonts";
import Layout from "@/components/layout/Layout";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${YekanBakh.className}`}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
