import type { Metadata } from "next";
import "./globals.css";
import { YekanBakh } from "@/utils/fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${YekanBakh.className}`}>
        {children}
      </body>
    </html>
  );
}
